language: java
jdk: "-openjdk11"
notifications:
  slack: online-shophq:Q881BC2QZosZhYex69lXehOz
after_success:
  - bash <(curl -s https://codecov.io/bash)
env:
  global:
    - CODECOV_TOKEN='29288651-646f-4abc-a401-427df5be45e7'
services:
  - postgresql
deploy:
  provider: heroku
  app: online-shop-tnt
  on:
    branch: master
  strategy: git
  api_key:
    secure: "BuuM4uGO43Bk1WLeh2/86o7bfTrGRAnFXx4BFifZaVDH8cmVpTvfxXxcqmYAjHlmOTe0SgVmw9HK2uiO3YMYHCmxv+OnkNrExDNM2a22r1P6SzSX5JlhqGIW7C+DHlKpqe4I32/LZy/02+KObQuRgCpooMFjomiT2dT5orJzkoyrnt2XlkON7FxV9btLjX9
    WJC7tzFkhMrkEqUpThht2GM8ztDB2o1adYNXWneOW9+TX+rZAQm2/FEZnG0XkxopdQhiJg1REK30nLmyP9ZxX40lc4Wr+CTHG5w4M33g835BFlvKq2f3eSLMXOiZqCtaovo8xMzohZ15+AeaiO9hSfv7UXF3W1zij7Hmyy4gThfKCS7n1NKHzDTdCvIxyKVy8ZlSmJX+1X
    WiSMg9raLiZKQcJiTP7PQ+Y11/h2IuMrShawgafLf1zQ8HFMOYpWhFxkkEt6L/BohGWFInzHf1l8kOcjrDpA7hIGNFeh/sklEkQ7yojR1lr43h+gHwWzJQNxOAJH15eyaEPNQHDyQo1Sd/gHq396qD0OnKnk7pV3ZyoIaOp9Zq1RK1oRJRwf2pTzR5lzNGq58iUjFU1yRh
    qIA9Q0hwJXqjpZJX5ARq8hRmLiCv4B4KFkV4L+wwbaPOOQR9lY5xMtsD8Zbuu/ntc8zqo1+Lsb7WQntAWMumzZmw="


