language: java
jdk: "-openjdk11"
notifications:
  slack: online-shophq:Q881BC2QZosZhYex69lXehOz
after_success:
  - bash <(curl -s https://codecov.io/bash)
env:
  global:
    - CODECOV_TOKEN='29288651-646f-4abc-a401-427df5be45e7'
services:
  - postgresql
deploy:
  provider: heroku
  app: online-shop-tnt
  on:
    branch: master
  strategy: git
  api_key:
    secure: e0lXlSof9ORrTVA3TduXB7BIDosVT1ji6nlsd8ywxK0wpVyv4Z71lFhdOaULoDZnVl7v3GfucGKtfvAQPl2ghklRjCn5KesA9MAb1ZE4xiwkOWXOk6eeieHNsMgUyoBSj/BZogxJY7j9XvRchBiJ9szVvM0RfD+JLSltsLGtz+vykjd17f7wLTi9nKb4sbH2D9Pf4DN2UiVPVLecLbwAd7YzoBXKTOmMPO29UufNE1yi3DB0PYsRcPXospCjADD+H023/Eqi2l+vh6LEgmr70LFJX7Gf0CyAOKvIHzHosc6LfIRrb6miIoycv40WqaudH+TPMJiOFnmpm9q9ysGSAtNJth22/bmNiqgcr/Ghpk2JoaEWxmUmpe8cinohCC3F3E2npxqTFIzzmuhpofzNnxpYl9cscFCrCqXCphD8MRSxbGooWdYAJYrS39R/u6Fh8uX6CvAwyEeqLIcyIhgDXBtjWSq4L+2daxlLpZL97qX4j9VKg64PnePUlZ9bokjZs08/8jxQ15Tc765CEBY0OQd1T8u1XGtfQpjmFEXEcsuTgG5or/8JSozlyb2vSHtL37/jb4n4ivNzM23gWtB2KmmukQUmujPZ1UifPnetzfLb01Zj3RCE8uXR3NXH+XE1Nv9uAcF/z2jVff5qVgLbNZtI7j2iTzv7JdtrEUB+eqo=